set -g prefix C-a
unbind C-b
set -s escape-time 5
set -g base-index 1

bind r source-file ~/.tmux.conf \; display ​"Reloaded!"
set -g mouse on
set -g status-keys vi
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi V send -X select-line
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel 'xclip -in -selection clipboard'
set -g default-terminal "tmux-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc"
set -g status-style fg=#89afef,bg=#070019
set -g window-status-current-format "#[reverse]#I:#W"
set-option -g history-limit 5000

bind | split-window -hc "#{pane_current_path}"
bind - split-window -vc "#{pane_current_path}"

bind -r "<" swap-window -d -t -1
bind -r ">" swap-window -d -t +1
# bind-key -n C-] send-keys C-]
bind c new-window -c "#{pane_current_path}"
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'christoomey/vim-tmux-navigator'

# bind-key -n C-] send-keys C-]
# tmux color plugin
# set -g @tmux_power_g0 "colour4"
# set -g @tmux_power_theme 'colour2'
# keep this line at the bottom
run '~/.tmux/plugins/tpm/tpm'
